name: CI/CD to EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: CI/CD to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code from master branch
        uses: actions/checkout@v1

      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: SCP to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_INSTANCE_DNS }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "dist/*"
          target: "/home/ubuntu/"

      - name: Restart PM2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_INSTANCE_DNS }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            rm -rf /home/ubuntu/personal-portfolio-frontend-old
            mv /home/ubuntu/personal-portfolio-frontend/ /home/ubuntu/personal-portfolio-frontend-old
            mv /home/ubuntu/dist/ /home/ubuntu/personal-portfolio-frontend
            pm2 restart portfolio-frontend || pm2 serve personal-portfolio-frontend 3001 --name "portfolio-frontend"
            pm2 save
